# coding=utf-8
"""
Constants module
"""

# Pins
PIN_MOTOR_SPEED_PWM = 25
PIN_MOTOR_IN1 = 17
PIN_MOTOR_IN2 = 27
PIN_ULTRASONIC_TRIG = 24
PIN_ULTRASONIC_ECHO = 22


# Ultrasonic
ULTRASONIC_SOUND_SPEED_Q = 17000
ULTRASONIC_MAX_DISTANCE = 2000
ULTRASONIC_LOOP_DELAY = 1
ULTRASONIC_START_DELAY = .3
ULTRASONIC_PING_DELAY = 0.00001


# Motor
MOTOR_SPEED_STEP = 100
MOTOR_MIN_SPEED = 4000
MOTOR_MAX_SPEED = 6000
MOTOR_DIRECTION_FORWARD = 1
MOTOR_DIRECTION_STOP = 0
MOTOR_DIRECTION_BACKWARD = -1


# Events (Pub/Sub channels)
CHANNEL_ALL = 'all'
CHANNEL_DISTANCE = 'distance'
CHANNEL_SPEED = 'speed'
CHANNEL_DIRECTION = 'direction'

SUBSCRIBER_EXIT_COMMAND = 'EXIT'